### ISSUE TITLE
No declaration file found for module '@ contentful / rich-text-html-renderer'.

### ISSUE THREAD

**Issue by larts85** [contentful/rich-text#259]
No declaration file found for module '@ contentful / rich-text-html-renderer'. 'X: /.../node_modules/@contentful/rich-text-html-renderer/dist/rich-text-html-renderer.es5.js' implicitly has type "any".
   Try "npm i --save-dev @ types / contentful__rich-text-html-renderer" if it exists or add a new declaration file (.d.ts) that includes "declare module '@ contentful / rich-text-html- renderer '; ". ts (7016)
   
Supposedly has the types builted-in. Any solution?

**Comment by seavan** [comment]
I am having the same problem here.

**Comment by djagya** [comment]
Hello @larts85 and @seavan, sorry for the inconvenience and your patience. We just released the 15.3.3 version, could you please try to build the project with it? Thank you.

**Comment by seavan** [comment]
@djagya problem persists with the version 15.3.3. typings are missing:
"typings": "dist/types/index.d.ts"

file dist/types/index.d.ts is not present in the package

**Comment by djagya** [comment]
Just released the version v15.3.4 of `rich-text-html-renderer` with the proper fix!
